import AppKit
import PasterCore
import SwiftData

/// 轮询 NSPasteboard.changeCount 监听剪贴板变化（macOS 没有剪贴板变化通知 API）。
@MainActor
final class ClipboardMonitor {
    private let context: ModelContext
    private var timer: Timer?
    private var lastChangeCount: Int

    private static let concealedType = NSPasteboard.PasteboardType("org.nspasteboard.ConcealedType")
    private static let transientType = NSPasteboard.PasteboardType("org.nspasteboard.TransientType")
    private static let autoGeneratedType = NSPasteboard.PasteboardType("org.nspasteboard.AutoGeneratedType")

    init(context: ModelContext) {
        self.context = context
        self.lastChangeCount = NSPasteboard.general.changeCount
    }

    func start() {
        guard timer == nil else { return }
        let t = Timer(timeInterval: 0.3, repeats: true) { [weak self] _ in
            MainActor.assumeIsolated {
                self?.checkPasteboard()
            }
        }
        RunLoop.main.add(t, forMode: .common)
        timer = t
    }

    func stop() {
        timer?.invalidate()
        timer = nil
    }

    /// PasteService 写回剪贴板后调用。直接把基线对齐到写入后的 changeCount，
    /// 这样写入之后其他应用的真实复制仍会产生增量并被正常记录。
    func ignoreNextChange() {
        lastChangeCount = NSPasteboard.general.changeCount
    }

    private var ignoredBundleIDs: Set<String> {
        let raw = UserDefaults.standard.string(forKey: "ignoredApps") ?? ""
        let ids = raw
            .split(whereSeparator: { $0.isNewline || $0 == "," })
            .map { $0.trimmingCharacters(in: .whitespaces) }
            .filter { !$0.isEmpty }
        return Set(ids)
    }

    private func checkPasteboard() {
        let pb = NSPasteboard.general
        guard pb.changeCount != lastChangeCount else { return }
        lastChangeCount = pb.changeCount

        let types = pb.types ?? []
        // 密码管理器等标记为「隐藏/瞬态」的内容不记录（剪贴板工具的行业约定）
        if types.contains(Self.concealedType) || types.contains(Self.transientType) || types.contains(Self.autoGeneratedType) {
            return
        }

        let frontApp = NSWorkspace.shared.frontmostApplication
        if let bundleID = frontApp?.bundleIdentifier, ignoredBundleIDs.contains(bundleID) {
            return
        }

        capture(from: pb, sourceApp: frontApp)
    }

    private func capture(from pb: NSPasteboard, sourceApp: NSRunningApplication?) {
        let bundleID = sourceApp?.bundleIdentifier
        let appName = sourceApp?.localizedName
        // 来源色在采集这一刻算好存进条目：iOS 的沙盒里取不到别的 App 的图标，
        // 卡片的淡染色只能靠 Mac 端同步过去的这个值
        let colorHex = AppIconProvider.headerColor(forBundleID: bundleID).srgbHexString

        if let urls = pb.readObjects(forClasses: [NSURL.self], options: [.urlReadingFileURLsOnly: true]) as? [URL],
           !urls.isEmpty {
            let paths = urls.map(\.path)
            insertDeduplicated(ClipItem(kind: .file,
                                        plainText: paths.joined(separator: "\n"),
                                        filePaths: paths,
                                        sourceAppBundleID: bundleID,
                                        sourceAppName: appName,
                                        sourceColorHex: colorHex))
            return
        }

        // 文本优先于图片：Excel/Numbers 等复制文本内容时会同时放一份 PDF/位图渲染，
        // 若先按图片处理，文本表示会永久丢失
        if let text = pb.string(forType: .string), !text.isEmpty {
            let rtf = pb.data(forType: .rtf)
            let kind = ClipClassifier.classify(text: text, hasRTF: rtf != nil)
            insertDeduplicated(ClipItem(kind: kind,
                                        plainText: text,
                                        rtfData: rtf,
                                        sourceAppBundleID: bundleID,
                                        sourceAppName: appName,
                                        sourceColorHex: colorHex))
            return
        }

        // 图片：优先直接取现成的 PNG 数据；只有 TIFF 时在后台线程转码，避免阻塞主线程
        if let png = pb.data(forType: .png) {
            insertImage(png, bundleID: bundleID, appName: appName, colorHex: colorHex)
        } else if let tiff = pb.data(forType: .tiff) ?? NSImage(pasteboard: pb)?.tiffRepresentation {
            // monitor 与应用同生命周期，强捕获 self 安全
            Task.detached(priority: .utility) {
                guard let rep = NSBitmapImageRep(data: tiff),
                      let png = rep.representation(using: .png, properties: [:]) else { return }
                await MainActor.run {
                    self.insertImage(png, bundleID: bundleID, appName: appName, colorHex: colorHex)
                }
            }
        }
    }

    private func insertImage(_ png: Data, bundleID: String?, appName: String?, colorHex: String?) {
        let item = ClipItem(kind: .image,
                            imageData: png,
                            sourceAppBundleID: bundleID,
                            sourceAppName: appName,
                            sourceColorHex: colorHex)
        item.imageHash = ContentHash.sha256(png)
        insertDeduplicated(item)
    }

    /// 与最近记录去重：内容相同则把旧条目提到最前，而不是重复插入。
    /// 同一套规则在 PasterCore 的 `ClipSaver` 里另有一份跨平台实现（iOS 主应用与扩展在用），
    /// 这里为避免 Mac 版回归没有改成调用它——改动去重条件或上限策略时两处都要改。
    private func insertDeduplicated(_ newItem: ClipItem) {
        var descriptor = FetchDescriptor<ClipItem>(sortBy: [SortDescriptor(\.createdAt, order: .reverse)])
        descriptor.fetchLimit = 50
        let recent = (try? context.fetch(descriptor)) ?? []

        if let duplicate = recent.first(where: { existing in
            switch newItem.kind {
            case .image:
                // 用内容哈希比较，避免把 externalStorage 的完整图片数据逐条读入内存
                return existing.kind == .image
                    && existing.imageHash != nil
                    && existing.imageHash == newItem.imageHash
            case .file:
                return existing.kind == .file && existing.filePaths == newItem.filePaths
            default:
                return existing.kind != .image && existing.kind != .file && existing.plainText == newItem.plainText
            }
        }) {
            duplicate.createdAt = Date()
            duplicate.sourceAppBundleID = newItem.sourceAppBundleID
            duplicate.sourceAppName = newItem.sourceAppName
            duplicate.sourceColorHex = newItem.sourceColorHex
            // 同一文本这次可能带来不同的富文本格式（或不再有），同步最新表示
            if newItem.kind != .image && newItem.kind != .file {
                duplicate.rtfData = newItem.rtfData
                duplicate.kindRaw = newItem.kindRaw
            }
            try? context.save()
            return
        }

        context.insert(newItem)
        trimHistory()
        // LSUIElement 应用没有常规窗口事件循环，autosave 不可靠，必须显式保存
        try? context.save()
    }

    /// 只统计未固定条目，超限时按时间删除最旧的；固定内容不占历史配额
    private func trimHistory() {
        let limit = UserDefaults.standard.integer(forKey: "historyLimit")
        guard limit > 0 else { return } // 0 = 无限制
        let unpinned = #Predicate<ClipItem> { $0.pinboard == nil }
        let count = (try? context.fetchCount(FetchDescriptor<ClipItem>(predicate: unpinned))) ?? 0
        guard count > limit else { return }
        var descriptor = FetchDescriptor<ClipItem>(predicate: unpinned,
                                                   sortBy: [SortDescriptor(\.createdAt, order: .reverse)])
        descriptor.fetchOffset = limit
        guard let overflow = try? context.fetch(descriptor) else { return }
        for item in overflow {
            context.delete(item)
        }
    }
}
